In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

X = np.array([
    [2.5, 2.4],
    [0.5, 0.7],
    [2.2, 2.9],
    [1.9, 2.2],
    [3.1, 3.0],
    [2.3, 2.7],
    [2.0, 1.6],
    [1.0, 1.1],
    [1.5, 1.6],
    [1.1, 0.9]
])

print("Original data:\n", X)

sc = StandardScaler()
X_scaled = sc.fit_transform(X)

pca = PCA(n_components=1)
X_new = pca.fit_transform(X_scaled)

print("\nData after PCA:\n", X_new)
print("\nVariance preserved:", pca.explained_variance_ratio_)


Original data:
 [[2.5 2.4]
 [0.5 0.7]
 [2.2 2.9]
 [1.9 2.2]
 [3.1 3. ]
 [2.3 2.7]
 [2.  1.6]
 [1.  1.1]
 [1.5 1.6]
 [1.1 0.9]]

Data after PCA:
 [[ 1.08643242]
 [-2.3089372 ]
 [ 1.24191895]
 [ 0.34078247]
 [ 2.18429003]
 [ 1.16073946]
 [-0.09260467]
 [-1.48210777]
 [-0.56722643]
 [-1.56328726]]

Variance preserved: [0.96296464]


In [1]:
import numpy as np

data = np.array([
    [170, 65],
    [180, 80],
    [160, 55],
    [175, 70],
    [165, 60]
])

print("Original Data:\n", data)
print("-" * 40)
m_val = np.mean(data, axis=0)
X_m = data - m_val

print("mean centered data:\n", X_m)
print("-" * 40)


cov = np.cov(X_m, rowvar=False)

print("covariance Matrix:\n", cov)
print("-" * 40)


Evalues, Evectors = np.linalg.eigh(cov)

print("eigenvalues:\n", Evalues)
print("eigenvectors:\n", Evectors)
print("-" * 40)


sindex = np.argsort(Evalues)[::-1]
seigenvalues = Evalues[sindex]
seigenvectors = Evectors[:, sindex]

print("sorted eigenvalues:\n", seigenvalues)
print("principal components \n", seigenvectors)
print("-" * 40)

pca_data = np.dot(X_m, seigenvectors)

print("Final PCA Transformed Data:\n", pca_data)
print("-" * 40)


Original Data:
 [[170  65]
 [180  80]
 [160  55]
 [175  70]
 [165  60]]
----------------------------------------
Mean Centered Data:
 [[  0.  -1.]
 [ 10.  14.]
 [-10. -11.]
 [  5.   4.]
 [ -5.  -6.]]
----------------------------------------
Covariance Matrix:
 [[62.5 75. ]
 [75.  92.5]]
----------------------------------------
Eigenvalues:
 [  1.0147073 153.9852927]
Eigenvectors:
 [[-0.77334214  0.63398891]
 [ 0.63398891  0.77334214]]
----------------------------------------
Sorted Eigenvalues:
 [153.9852927   1.0147073]
Principal Components (Sorted Eigenvectors):
 [[ 0.63398891 -0.77334214]
 [ 0.77334214  0.63398891]]
----------------------------------------
Final PCA Transformed Data:
 [[ -0.77334214  -0.63398891]
 [ 17.16667903   1.14242327]
 [-14.84665261   0.75954345]
 [  6.26331309  -1.33075508]
 [ -7.80999738   0.06277727]]
----------------------------------------
